export interface SummarizeExercise {
    id: number;
    title: string;
    instructions: string;
    text: string;
  }
  
  export const pteSummarizeExercises: SummarizeExercise[] = [
        {
          id: 23,
          title: "Education Quality vs Equity in Australia",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `In Australia, debates about education often assume that quality and equity cannot coexist. Curriculum reforms aiming to improve equity sometimes fail because new offerings are not equally effective for all students. Disadvantaged students may take up differentiated courses that do not fully support learning outcomes. Evidence from New South Wales illustrates these challenges. Improving quality is crucial for human capital and economic development, while equity ensures social cohesion and fair opportunity. Education systems must balance high-quality instruction with access for all students. Disparities in learning outcomes often reflect social background, limiting the potential of reforms. Effective policies should address both quality and equity, ensuring disadvantaged students can benefit from advanced educational offerings. International comparisons show similar struggles, highlighting the need for adaptive strategies. By integrating differentiated instruction, teacher training, and resource allocation, schools can enhance outcomes for all learners. Social cohesion and the development of high-level skills depend on systems that do not simply replicate existing inequalities but actively reduce them. Educational planning should consider the complex interplay between policy, student background, and curriculum implementation. The ultimate goal is to create equitable, high-quality education accessible to all social groups, contributing to both economic progress and social stability. This requires continuous assessment, innovative approaches, and evidence-based interventions to close gaps while raising overall standards.`
        },
        {
          id: 22,
          title: "Allowances and Financial Education for Children",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `Paying children allowances for extra household work can teach financial responsibility. Allowances help children understand earning, saving, spending, giving, and investing. Saving demonstrates goal-setting, cost-cutting, and planning for the future. Many banks offer youth accounts to illustrate the power of compound interest, showing how money grows over time. For example, investing one dollar at two percent interest compounds yearly. By managing allowances, children learn money management skills and the consequences of financial decisions. These lessons also foster independence, decision-making, and understanding of economic principles. Using allowances to teach practical financial knowledge helps children prepare for adult responsibilities. It also encourages critical thinking about budgeting and prioritizing needs versus wants. In addition, giving children the opportunity to save for goals instills patience and perseverance. Families can balance work, rewards, and education by creating structured allowance programs. This approach highlights the value of experiential learning, bridging theory and practice in financial literacy. Beyond personal finance, allowances can also nurture social responsibility if children donate a portion to charitable causes. Ultimately, managing money through allowances builds foundational skills essential for lifelong financial competence, independence, and informed economic behavior. By combining real-life experiences with guidance, children develop confidence and habits that carry into adulthood, preparing them for complex financial environments.`
        },
        {
          id: 21,
          title: "Cows and Grass Co-Evolution",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `The co-evolution between cows and grass illustrates ecological interdependence. Grass has adapted to withstand grazing, while cows maintain and expand grass habitats, spread seeds, and fertilize soil. In exchange, ruminants like cows convert indigestible grass into high-quality protein using the rumen, a specialized fermentation organ. This symbiosis benefits both species: grass reproduces and thrives, and cows obtain nutritious food. Understanding this relationship provides insight into meat production, grazing management, and ecosystem sustainability. The rumen’s bacteria digest cellulose, supporting cows’ growth and the global food supply. This co-evolution demonstrates natural efficiency and balance, highlighting the importance of maintaining grazing ecosystems. Farmers and environmental scientists study this interaction to optimize livestock nutrition, soil health, and pasture sustainability. Proper grazing management preserves biodiversity, reduces erosion, and supports ecological equilibrium. The cow-grass system exemplifies mutual adaptation over millions of years, combining evolutionary biology with agricultural practices. It also underlines the significance of ruminants in food chains, energy transfer, and maintaining habitats. Recognizing this balance allows for responsible animal husbandry, ensuring ecological integrity while meeting human nutritional demands. The relationship emphasizes the role of evolved biological systems in shaping ecosystems and providing sustainable resources for both animals and humans.`
        },
        {
          id: 20,
          title: "Tourism in Malaysia",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `Malaysia is a diverse and appealing Southeast Asian destination, combining modern cities, beaches, mountains, and national parks. Kuala Lumpur features the Petronas Twin Towers and Batu Caves, a limestone temple with ornate Hindu shrines. Borneo’s Sabah region offers Sipadan Island, Mount Kinabalu, and the Sepilok Orang Utan Sanctuary. Activities include diving, white-water rafting, and wildlife observation. Historical Malacca offers cultural heritage and colonial architecture, while Penang showcases Chinese culture and cuisine. Malaysia’s tourism campaign targets 20 million visitors, promoting natural beauty, adventure, and cultural experiences. Tourists benefit from a variety of attractions, from urban landmarks to ecological wonders. The combination of nature, history, and modern infrastructure creates a unique and memorable experience. Visitors can explore islands, mountains, wildlife reserves, and ancient sites, gaining insight into Malaysia’s rich cultural and ecological diversity. The country balances adventure tourism with cultural education, offering both relaxation and exploration. Malaysia’s infrastructure supports travel convenience, enhancing visitor engagement. Tour operators, conservationists, and local communities collaborate to ensure sustainable tourism practices. The diversity of experiences caters to all traveler types, from adventure seekers to cultural enthusiasts. Malaysia’s commitment to tourism growth highlights economic, environmental, and social opportunities while preserving national heritage. Tourists can enjoy vibrant cities, pristine beaches, and immersive natural landscapes, making Malaysia a premier travel destination in Southeast Asia.`
        },
        {
          id: 19,
          title: "Country Living Experience",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `A person born on a farm reflects on returning to rural life after years in the city. Despite challenges like limited heating, occasional water issues, and blocked roads, the advantages of country living outweigh the disadvantages. The slower pace, natural surroundings, and space for family life create a more fulfilling environment. Persuading a city-born spouse required emphasizing lifestyle benefits. Rural living offers tranquility, connection with nature, and practical knowledge, balancing inconveniences with overall quality of life. The individual draws on personal experience to adapt and appreciate agricultural routines. Farming knowledge, self-sufficiency, and outdoor activities enhance personal well-being and family cohesion. Compared to city life, rural living provides more direct engagement with the environment, including seasonal cycles and local community ties. Understanding both advantages and minor setbacks allows residents to make informed lifestyle choices, highlighting the appeal of countryside living. This experience shows how familiarity with rural conditions influences expectations, satisfaction, and long-term adaptation.`
        },
        {
          id: 18,
          title: "Hiring Overqualified Workers",
          instructions: "Write a summary of the passage using 50–75 words.",
          text: `Research shows that overqualified job applicants often perform better than expected and do not leave sooner. Companies typically avoid hiring such candidates due to bias, seeking a “perfect fit” instead. Studies reveal dissatisfaction can be mitigated through empowerment and autonomy in decision-making. Overqualified employees contribute advanced skills and experience, benefiting organizations when properly managed. Managers should recognize this talent pool as an opportunity, not a liability, and implement strategies that maximize engagement and performance. Empowerment reduces frustration and turnover, turning potential issues into advantages. By understanding motivations, managers can optimize workforce allocation and tap into the expertise of highly skilled individuals. Overqualified workers often bring innovation, efficiency, and leadership potential. Proper integration can enhance team performance, organizational adaptability, and knowledge sharing. Recognizing the value of these employees requires rethinking conventional hiring practices. The growing pool of highly educated or experienced candidates offers strategic opportunities for companies to strengthen operations, improve outcomes, and maintain competitive advantage.`
        },
    
  {
    id: 17,
    title: "Plug-in Electric Vehicles",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Plug-in electric vehicles (PEVs) represent the future of urban transport. Drivers charge batteries overnight, use them for city commutes, and can feed electricity back to the grid. Contracts with electricity suppliers allow selling surplus energy, benefiting both parties. Hybrid engines ensure range during low battery conditions. Rising concerns about greenhouse gas emissions and peak oil make petroleum reliance unsustainable. PEVs combine efficient, low-emission travel with grid integration, offering an eco-friendly, economically viable alternative. Battery technology, smart charging, and grid feedback create flexibility and sustainability. PEV adoption can reduce fossil fuel dependency, urban pollution, and operating costs. As infrastructure develops, more users will benefit from incentives, battery management systems, and energy trading possibilities. Policies, regulations, and technological innovations will shape the evolution of transportation systems, promoting cleaner cities. PEVs align with global environmental goals and energy strategies, integrating mobility with sustainable electricity use. Governments and manufacturers are working to expand networks, improve battery performance, and educate the public. This shift may transform daily commuting, urban planning, and energy consumption patterns. Ultimately, PEVs demonstrate a practical, environmentally conscious solution for future mobility challenges, combining efficiency, adaptability, and long-term sustainability. Users participate actively in energy management, fostering a collaborative relationship with the power grid. This approach benefits cities, individuals, and the planet, while addressing urgent climate and energy concerns effectively.`
  },
  {
    id: 16,
    title: "Cleaning the Rosetta Stone",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `The Rosetta Stone, discovered in 1799, accumulated layers from copies, handling, and preservation attempts. In 1999, the British Museum’s Cracking Codes exhibition initiated careful cleaning to remove grease, wax, ink, and modern paint while preserving original carvings. Analytical techniques guided the process, ensuring the protection of ancient inscriptions. A small square was left untouched to illustrate previous coatings. The project combined conservation science, historical research, and careful restoration to reveal and protect one of history’s most important archaeological artifacts, highlighting its historical and educational significance. Modern methods allowed analysis of residues, ensuring minimal risk to the original surface. This work emphasized precision, patience, and interdisciplinary collaboration in heritage preservation. Visitors learned both the artifact’s content and its complex conservation story. The careful cleaning revealed the contrast between centuries of handling and the original engraved text. This approach serves as a model for future conservation projects. The Rosetta Stone’s significance extends beyond its linguistic value to include exemplary preservation practices. Techniques applied illustrate how science and history intersect in cultural heritage management, ensuring longevity and accessibility for research and public engagement.`
  },
  {
    id: 15,
    title: "Television vs Reading Vividness",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Television presents a fully formed, visually vivid simulation of reality that triggers instinctive responses, unlike reading, which requires active brain engagement to interpret abstract symbols. Reading activates reasoning centers, fostering reflection, analysis, and understanding. Television’s immediacy and realism bypass logic, creating powerful emotional impact but limiting critical thinking. Books demand cognitive participation to construct reality, offering moderated engagement. This distinction affects perception, learning, and the way audiences consume information, highlighting differences in cognitive processing between media formats. The immersive experience of television captures attention quickly but can reduce analytical engagement. Printed texts allow deeper mental simulation, reflection, and internal visualization. Both mediums convey information effectively, but their cognitive impact differs fundamentally. Understanding these differences informs media literacy, teaching methods, and content presentation strategies. Consumers’ interpretation of events is shaped by the medium, influencing opinion formation, memory retention, and reasoning. Educators can leverage these differences to optimize learning, combining visual and textual methods. Awareness of the contrasting cognitive demands helps balance emotional engagement with critical thinking skills, emphasizing media’s role in shaping understanding and responses. Both television and reading offer complementary experiences, with implications for education, communication, and media design.`
  },
  {
    id: 14,
    title: "Prohibition and American Wine Industry",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `The 18th Amendment and Volstead Act (1920) nearly destroyed the American wine industry by prohibiting alcohol production and sale. Loopholes allowed sacramental and medicinal wine, plus limited fruit juice production. Bootleggers exploited these loopholes, but the government soon banned grape juice sales, halting illegal wine production. Vineyards ceased planting, causing industry collapse. Prohibition disrupted growth, entrepreneurship, and innovation in winemaking, illustrating how legal restrictions can profoundly impact industries, local economies, and cultural traditions. The period led to underground markets and creative responses to restrictive laws. Loss of commercial activity, expertise, and market access weakened the wine sector. Post-prohibition, the industry required decades to rebuild. Prohibition’s consequences highlight the importance of regulatory balance in preserving economic viability, cultural practices, and public demand. Lessons from this era inform contemporary policy, alcohol regulation, and business adaptation strategies. Government intervention reshaped supply, demand, and production patterns, affecting livelihoods and trade networks. The historical case demonstrates how policy can inadvertently stimulate illicit markets, reduce innovation, and permanently alter industry structures. Understanding these dynamics is key for policymakers and entrepreneurs in navigating legal and economic environments effectively, balancing regulation with industry sustainability and growth.`
  },
  {
    id: 13,
    title: "Honey as an Athletic Supplement",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Studies show honey can enhance athletic performance with fewer negative effects than traditional carbohydrate gels. Clinical trials reveal honey has a milder effect on blood sugar and may speed muscle recovery when combined with protein supplements. Research with athletes demonstrated benefits in endurance and post-workout recovery. Honey offers a natural alternative to synthetic supplements, promoting energy, nutrient absorption, and balanced glucose levels. Its bioactive components support metabolism, performance, and health. Incorporating honey in training regimens can improve overall fitness, sustain energy levels, and enhance recovery after intense exercise. Athletes gain a safe, efficient, and sustainable source of carbohydrates and antioxidants. The studies highlight honey’s potential to replace traditional sports nutrition products. Controlled consumption can optimize benefits, prevent spikes in blood sugar, and contribute to long-term physical health. This approach aligns with natural, evidence-based sports nutrition, emphasizing functional foods in athletic performance. Research continues to explore optimal dosage, timing, and combinations with other nutrients for enhanced outcomes. Honey’s accessibility, taste, and versatility make it a practical addition to diet and supplementation strategies for active individuals. Natural alternatives like honey reduce dependency on synthetic gels while supporting recovery, energy, and metabolic efficiency. Athletes benefit from both physiological and nutritional properties in a holistic approach to performance enhancement.`
  },
  {
    id: 12,
    title: "Skipping Breakfast and Its Effects",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Skipping breakfast negatively affects learning, memory, and physical performance. Students who skip breakfast struggle with attention, problem-solving, and verbal fluency. Adults also experience impaired cognition. A nutritious breakfast, such as cereal with milk, improves mental and physical performance. Low-sugar options and nonfat milk are recommended. For children, breakfast is often a learned habit rather than a biological necessity. Regular morning meals enhance focus, memory retention, and energy. Research confirms breakfast supports academic achievement, cognitive function, and overall well-being. Establishing consistent routines, particularly in school-aged children, promotes learning efficiency. The right nutritional choices prevent blood sugar spikes and provide steady energy. Families play a role in shaping breakfast habits, encouraging healthy, sustainable eating practices. Skipping breakfast can diminish alertness, information processing, and mental agility throughout the day. Nutrient-rich morning meals supply essential vitamins, minerals, and macronutrients for optimal performance. Early dietary interventions can influence long-term health and productivity. Combining education, accessibility, and proper meal planning ensures children and adults maximize the cognitive and physical benefits of breakfast. This simple practice supports daily routines, academic success, and general wellness, reinforcing the importance of a balanced morning meal. Consistency and nutrition quality are key factors in maintaining energy and cognitive performance throughout the day.`
  },

  {
    id: 11,
    title: "Digital Communication and Social Skills",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Digital communication has transformed social interactions, influencing both online and offline relationships. While platforms enable instant contact, they often reduce face-to-face engagement and nonverbal cues, potentially affecting empathy, emotional intelligence, and conflict resolution. Young users adapt quickly, developing new social norms, but may experience difficulty interpreting subtle social signals. Studies show online communication enhances connectivity and information sharing but may also foster superficial interactions and reduce long-term bonding. Digital tools facilitate collaboration, learning, and networking across distances. Social media allows expression, identity exploration, and cultural exchange, yet excessive use can contribute to isolation, distraction, or mental health challenges. Balancing online and offline interactions is critical to maintaining emotional resilience, healthy relationships, and effective communication skills. Educational strategies promote digital literacy, guiding safe, responsible, and meaningful use of technology. Communication habits evolve with technological advancement, impacting personal development, professional opportunities, and societal norms. Users who cultivate critical awareness and intentional engagement can maximize benefits while minimizing negative effects. Social dynamics now integrate digital presence, shaping perceptions, influence, and collaboration patterns. Monitoring screen time, fostering face-to-face interactions, and developing empathy are essential. Understanding the cognitive, emotional, and behavioral impacts of digital communication informs parenting, teaching, and workplace practices, supporting social growth in a digitally connected world. Digital communication reshapes daily life, relationships, and skill development, requiring conscious adaptation and reflection to optimize outcomes.`
  },
  {
    id: 10,
    title: "Renewable Energy and Grid Integration",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Renewable energy sources, such as solar and wind, are increasingly integrated into power grids, reducing dependence on fossil fuels. Variable generation requires advanced grid management, energy storage, and smart distribution systems. Governments and utilities invest in infrastructure, forecasting, and incentives to support adoption. Renewable integration lowers greenhouse gas emissions, diversifies energy supply, and enhances resilience. Challenges include intermittency, cost, and system stability, which are addressed through technological innovation and policy frameworks. Grid modernization ensures efficient energy transmission and demand response. Storage solutions, such as batteries and pumped hydro, buffer fluctuations and maintain reliability. Decentralized energy production empowers consumers to participate in energy markets, feeding surplus power into grids. Collaboration between industry, regulators, and researchers promotes innovation and cost reduction. Long-term sustainability depends on balancing production, consumption, and environmental protection. Public engagement and policy alignment accelerate transition to low-carbon energy systems. Renewable energy contributes to climate goals, energy security, and economic growth. Effective planning, forecasting, and technological integration maximize benefits while minimizing disruption. Ongoing monitoring, evaluation, and adaptive strategies improve performance and support policy decisions. Grid integration transforms energy systems, ensuring a cleaner, more reliable, and economically viable future. Adoption of renewables is essential to meet global climate commitments and reduce environmental impact.`
  },
  {
    id: 9,
    title: "Water Conservation Techniques",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Water conservation is critical in addressing scarcity, environmental sustainability, and resource management. Techniques include rainwater harvesting, drip irrigation, wastewater recycling, and low-flow appliances. Behavioral changes, such as reducing wastage, fixing leaks, and mindful consumption, complement technological solutions. Communities, governments, and industries implement policies, incentives, and education programs to promote efficiency. Conserving water supports agriculture, industry, and human health, mitigating climate change effects and preserving ecosystems. Long-term planning ensures sustainable supply. Monitoring and assessment identify critical areas and measure progress. Public awareness campaigns and participatory initiatives encourage responsible use. Innovations in treatment, storage, and distribution enhance efficiency. Sustainable practices reduce energy consumption associated with pumping, treatment, and heating. Urban and rural strategies adapt to local conditions, population growth, and environmental constraints. Integrating conservation with planning, policy, and technology ensures resilient water systems. Stakeholders collaborate to balance supply, demand, and ecological needs. Conservation contributes to economic savings, social equity, and environmental protection. Prioritizing efficient use preserves water for future generations. Global cooperation and knowledge sharing optimize implementation. Educating the public fosters culture of sustainability, making water stewardship part of everyday behavior. This multi-level approach safeguards resources, strengthens resilience, and supports long-term development. Efficient water use is a cornerstone of environmental sustainability and human well-being, ensuring a reliable supply in changing climates.`
  },
  {
    id: 8,
    title: "Impact of Sleep on Cognitive Performance",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Sleep plays a vital role in cognitive performance, memory consolidation, emotional regulation, and physical health. Insufficient or poor-quality sleep impairs attention, problem-solving, and decision-making. Research demonstrates that REM and deep sleep stages facilitate learning, creativity, and mental processing. Adolescents, adults, and elderly individuals require different durations, yet most populations suffer chronic sleep deficits due to lifestyle, work, and technology use. Prioritizing consistent sleep schedules, sleep hygiene, and environment improves alertness, performance, and well-being. Strategic napping, relaxation techniques, and limiting screen exposure enhance restorative sleep. Cognitive decline, mood disturbances, and physical health risks increase with persistent deprivation. Educational campaigns and workplace policies promote awareness of sleep’s importance. Monitoring sleep patterns helps identify issues and implement solutions. Balanced sleep supports neuroplasticity, emotional resilience, and efficient information processing. Healthcare providers emphasize sleep assessment as part of holistic care. Aligning circadian rhythms with daily schedules optimizes function. Sleep interventions can enhance learning outcomes, workplace productivity, and mental health. Awareness of individual differences in sleep needs enables tailored approaches. Long-term benefits include reduced risk of chronic diseases, improved mood stability, and sustained cognitive abilities. Recognizing sleep as essential, not optional, fosters healthy, productive lifestyles across age groups and social contexts. Adequate sleep is foundational to optimal cognitive function, emotional stability, and overall quality of life.`
  },
  {
    id: 7,
    title: "Effects of Urbanization on Biodiversity",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Urbanization dramatically impacts biodiversity through habitat fragmentation, pollution, introduction of invasive species, and altered land use. Native species decline as green spaces shrink, while adaptable species proliferate. Urban planning, green infrastructure, and conservation corridors mitigate effects. Monitoring wildlife populations, restoring habitats, and promoting ecological connectivity support resilience. Sustainable urban design balances human development with ecological preservation. Public education encourages responsible stewardship. Policies integrating biodiversity protection into construction, transportation, and waste management maintain ecosystem services. Research highlights species adaptation, migration, and extinction risks. Ecosystem degradation affects climate regulation, water quality, and soil fertility, impacting human well-being. Biodiversity-rich cities enhance recreation, aesthetics, and cultural value. Collaboration between ecologists, planners, and policymakers strengthens urban ecosystems. Implementing native plant landscaping, green roofs, and wildlife-friendly infrastructure fosters coexistence. Urbanization requires innovative solutions to maintain species diversity. Restoration projects, protected zones, and environmental assessments reduce negative consequences. Understanding ecological principles and human impact guides sustainable development. Integrating biodiversity considerations into legislation, urban design, and community initiatives preserves species and supports ecological balance. Maintaining habitat connectivity ensures genetic diversity and resilience to climate change. Strategic urban management reconciles population growth with environmental stewardship, securing long-term ecosystem stability. Conserving biodiversity enhances urban livability, health, and resilience while sustaining essential ecological functions for present and future generations.`
  },
  {
    id: 6,
    title: "Artificial Intelligence in Healthcare",
    instructions: "Write a summary of the passage using 50–75 words.",
    text: `Artificial Intelligence (AI) is transforming healthcare through diagnostics, personalized treatment, and predictive analytics. Machine learning algorithms analyze medical images, patient records, and genetic data to detect diseases earlier and more accurately. AI-driven decision support assists clinicians in treatment planning and risk assessment. Telemedicine, virtual assistants, and robotic surgery improve access, efficiency, and precision. Ethical considerations, data privacy, and bias mitigation are essential for responsible implementation. Integration of AI enhances patient outcomes, reduces errors, and optimizes resource allocation. Ongoing research develops smarter models capable of learning from complex datasets. Collaboration between technologists, medical professionals, and regulators ensures safety and efficacy. AI applications include disease prediction, drug discovery, patient monitoring, and operational management. Continuous evaluation and validation are necessary to maintain reliability and public trust. Human oversight complements AI insights, combining computational efficiency with clinical judgment. Adoption challenges include infrastructure, training, and cost, yet potential benefits justify investment. Personalized healthcare, informed decision-making, and proactive interventions are key outcomes. AI facilitates preventive medicine, early intervention, and population health management. Responsible integration balances innovation, ethics, and patient-centered care. Future developments promise adaptive, intelligent systems supporting healthcare delivery. Patients, providers, and policymakers must navigate opportunities and risks carefully. Ethical, technical, and social frameworks guide sustainable AI deployment. AI empowers precision medicine, improves efficiency, and strengthens global health outcomes. Interdisciplinary collaboration drives innovation and ensures practical, safe, and equitable application of AI in healthcare environments.`
  },


    {
      id: 1,
      title: "Prior Knowledge in Learning",
      instructions: "Write a summary of the passage using 50–75 words.",
      text: `Prior knowledge, also called pre-existing knowledge, refers to the skills, abilities, and understanding a learner brings to a new educational situation. This includes all knowledge acquired formally or informally in any context before the learning event. Learners need sufficient prior knowledge to make connections with new material. Teachers often activate prior knowledge at the start of lessons or topics to help students recall previous content. Activating prior knowledge helps learners link new and old information, making learning more meaningful. It can involve classroom activities, discussions, or reminders from past lessons. Theoretical frameworks suggest this process activates specific mental schemas, which improve comprehension and retention. In practical terms, it encourages students to think critically about the topic and prepares them for deeper engagement. Effective activation of prior knowledge is considered a crucial step in instructional design, fostering understanding and enhancing students’ ability to integrate and apply new concepts across different learning scenarios. By recalling prior experiences, learners can identify patterns, anticipate outcomes, and develop problem-solving skills. Educators emphasize creating opportunities for students to express what they already know and scaffold new knowledge accordingly. Overall, prior knowledge serves as the foundation upon which new learning is built, ensuring educational experiences are connected, relevant, and effective.`
    },
    {
      id: 2,
      title: "Straw as a Sustainable Building Material",
      instructions: "Write a summary of the passage using 50–75 words.",
      text: `Straw has been researched as a low-impact building material for over a decade, with innovative developments leading to industry certifications. The BM TRADA’s Q-Mark certification ensures energy efficiency, fire safety, durability, and weather resilience for straw buildings. Prefabricated ModCell panels, combining wooden frames with straw or hemp, offer twice the insulation required by UK standards. Monitoring shows potential fuel bill reductions up to 90%. Straw’s carbon absorption and low construction footprint make it environmentally beneficial and potentially carbon negative. These advances enable developers and homeowners to secure insurance and mortgages for straw homes, demonstrating the practical viability of sustainable construction. The combination of durability, insulation efficiency, and carbon reduction represents a significant step forward in eco-friendly architecture. Straw buildings also provide a practical example of how agricultural by-products can be repurposed to meet modern housing demands while reducing environmental impact. This research emphasizes the importance of performance data in validating sustainable technologies, ensuring they are safe, cost-effective, and widely adoptable. As cities and developers seek low-carbon alternatives, straw construction offers a promising model for future residential and commercial buildings. These developments highlight the intersection of environmental responsibility, innovative design, and practical implementation in sustainable building practices. The application of scientific monitoring ensures long-term performance, reliability, and consumer confidence in new green technologies, making straw a credible alternative to conventional construction materials.`
    },
    {
      id: 3,
      title: "Deep-Sea Mining and Environmental Risks",
      instructions: "Write a summary of the passage using 50–75 words.",
      text: `The National Oceanography Center (NOC) researches deep-sea mineral resources, which are essential for low-carbon technologies. Using ocean robots, the NOC assesses the environmental impacts of potential mining activities. Recent expeditions discovered sufficient Tellurium for UK solar panel needs, but deep-sea nodule mining can cause decades-long damage to marine life. Nodules contain metals like copper and nickel and grow slowly over millions of years. With global population projected to reach nine billion by 2050, ocean resources are increasingly targeted for energy, food, and minerals. NOC research aims to provide evidence-based guidance for future decisions, balancing resource use and environmental protection. Their studies highlight the tension between technological demand and ecological preservation. Deep-sea mining presents economic opportunities but also long-term ecological risks, emphasizing the need for careful management. Scientific monitoring informs policymakers and industries about sustainable practices. By understanding growth rates, habitat disruption, and species sensitivity, NOC supports policies that mitigate environmental harm while exploring resource potential. This research ensures that future exploitation of ocean resources is grounded in rigorous evidence, protecting biodiversity and informing ethical resource utilization for a growing human population. The center’s findings are critical in preparing for responsible use of deep-sea mineral resources while addressing global energy and material needs.`
    },
    {
      id: 4,
      title: "Dogs and Emotional Recognition",
      instructions: "Write a summary of the passage using 50–75 words.",
      text: `Dogs have developed skills to interact with humans by recognizing emotional cues in voice, posture, odor, and facial expressions. A study with 26 feeding dogs exposed them to photos of faces expressing six basic emotions. Dogs exhibited higher stress levels and longer pauses in feeding when seeing anger, fear, or happiness. They turned their heads asymmetrically, depending on the emotion observed. This supports the theory that dogs’ brains process human emotions asymmetrically, demonstrating sophisticated interspecies communication. Emotional recognition allows dogs to respond appropriately to humans’ moods, enhancing their social bonds and cooperative behavior. The study highlights how domestication and close human contact shaped canine cognitive abilities, enabling them to interpret subtle cues in human behavior. Such abilities have evolutionary advantages for survival and social integration in human environments. The findings also contribute to understanding animal cognition, showing that dogs are sensitive to emotions and capable of adaptive behavioral responses. Recognizing human emotional states improves dogs’ ability to interact effectively and strengthens human-animal relationships, illustrating complex cross-species social cognition. This research informs training, welfare practices, and enrichment activities, emphasizing the importance of emotional awareness in domesticated animals.`
    },
    {
      id: 5,
      title: "Sustainable Development Concepts",
      instructions: "Write a summary of the passage using 50–75 words.",
      text: `The Brundtland Report (1987) defines sustainable development as meeting present needs without compromising future generations. Past development focused on growth and innovation but often failed to predict future needs. Critics argue that sustainability assumptions are static, underestimate resources, exaggerate problems, and link environmental policies incorrectly to poverty or profit. For a better future, society must challenge these assumptions. Sustainable development requires flexibility, recognizing evolving circumstances, and leveraging human ingenuity. Effective planning should integrate social, economic, and environmental dimensions, balancing progress and equity. Understanding future uncertainties allows policymakers to design adaptive strategies. Sustainable development is not merely environmental protection but also includes economic resilience and social cohesion. By considering technological advances, resource management, and shifting societal priorities, sustainability can become actionable. It demands innovation, monitoring, and assessment to ensure that policies remain relevant over time. The dynamic approach contrasts with rigid frameworks, fostering creativity and problem-solving. Education, community engagement, and evidence-based interventions are critical in achieving sustainable outcomes. Recognizing that past assumptions may no longer hold helps societies develop flexible, effective strategies to address evolving environmental and social challenges.`
    },
    
  ];
  