export interface Sentence {
    text: string;
    audio: string;
  }
  
  const sentences: Sentence[] = [
    { text: "Sustainable tourism is a concept vital to preserving the world's cultural and natural heritage. This responsible travel philosophy is about making a positive impact on the environments we visit and the communities we encounter. Firstly, sustainable tourism is about respecting and contributing to local cultures. It involves engaging with tradition, supporting artisan markets, and preserving historical sites. By doing so, we become not just tourists, but advocates for cultural preservation. Secondly, it emphasizes environmental conservation. By choosing eco-friendly accommodations and activities, we minimize our carbon footprint. Practices like leaving no trace and reducing plastic use help protect natural landscapes and wildlife. As we venture out to explore the world, let's commit to sustainable tourism practices. Our conscious choices ensure that the beauty and diversity of our global destinations remain for future travellers to appreciate.", audio: "https://res.cloudinary.com/ddy824awb/video/upload/v1761836603/RetellLecture/wfd1.mp3" },
    { text: "In the midst of our academic pursuits, let us not overlook a fundamental truth: the profound connection between diet and mental health. What we eat fuels not only our bodies but also our minds. Nutritional psychiatry is an emerging field revealing how our dietary choices impact our mood and mental well-being. Foods rich in omega-3 fatty acids, for example, are not merely good for the heart but are also linked to reduced rates of depression. Additionally, the gut-brain axis presents a fascinating narrative of communication between our digestive systems and mental states. The microbiome in our intestines may influence everything from our stress levels to our thought processes, making balanced, mindful eating an essential component of mental fitness. As we navigate the complexities of college life, let us be mindful of the sustenance we choose. A well-nourished body can be the vessel of a well-nourished mind, enabling us to reach the zenith of our intellectual and emotional capacities.In the panorama of skills vital for success, emotional intelligence shines prominently. It's the ability to be aware of, control, and express our emotions judiciously and empathetically that marks our path, not just through academia, but through life. Emotional intelligence is crucial in developing robust relationships, both personal and professional. It equips us with the sensitivity to navigate social complexities, leading to more fruitful collaborations and deeper connections. Studies in organizational behavior find that teams with high emotional intelligence have increased effectiveness, higher job satisfaction, and better outcomes. Beyond interaction, emotional intelligence is integral to self-awareness. It allows us to reflect, understand our strengths and weaknesses, and pursue personal growth. This introspective aspect is not only a cornerstone for mental well-being but also a catalyst for academic and career success. As we march towards our future, let's invest in our emotional intelligence. It is this investment that will yield dividends in all facets of our lives, forging paths to leadership and fulfilment.", audio: "https://res.cloudinary.com/ddy824awb/video/upload/v1761836637/RetellLecture/wfd2.mp3" },
  ];
  
  export default sentences;
  