export interface RespondSituation {
    id: number;
    title: string;
    situation: string;
    expectedAnswer: string;
    type: "respond_to_situation";
  }
  
  const respondSituations: RespondSituation[] = [
    {
      id: 50,
      title: "Adapting Lessons for Learning Difficulties",
      situation: `You are organizing a seminar on special education. Some teachers are unsure about adapting lessons for children with learning difficulties. Explain why personalized teaching approaches are essential and how they can be applied.`,
      expectedAnswer: `Personalized teaching recognizes that every student learns differently. Using tools like visual aids, scaffolding, and hands-on activities helps bridge gaps. Tailored strategies also improve confidence and foster inclusion.`,
      type: "respond_to_situation",
    },
    {
      id: 49,
      title: "Inclusive Education Strategies",
      situation: `You are attending a policy meeting on inclusive education. Officials ask how schools can better support students from diverse backgrounds and with special needs.`,
      expectedAnswer: `Schools can train staff in cultural competency, adopt multilingual resources, and develop individualized learning plans. Promoting representation in staff and curriculum also helps students feel valued.`,
      type: "respond_to_situation",
    },
    {
      id: 48,
      title: "Importance of Arts in Education",
      situation: `A parent asks why the arts are important when academic subjects fill most of the curriculum. Explain their value.`,
      expectedAnswer: `The arts boost creativity, emotional awareness, and problem-solving skills. They help students express themselves and improve mental health while complementing core academic learning.`,
      type: "respond_to_situation",
    },
    {
      id: 47,
      title: "Engaging Students in STEM",
      situation: `You are promoting STEM education. Students find it difficult and boring. Explain how to make these subjects more engaging.`,
      expectedAnswer: `Use project-based learning, real-world examples, and digital tools like simulations. Highlight diverse role models to break stereotypes and create a collaborative learning environment.`,
      type: "respond_to_situation",
    },
    {
      id: 46,
      title: "Value of Vocational Education",
      situation: `Many students are unsure whether vocational training is worthwhile. Explain its economic and practical value.`,
      expectedAnswer: `Vocational programs build hands-on skills needed by industries. They offer faster employment, lower costs than degrees, and support local economic growth.`,
      type: "respond_to_situation",
    },
    {
      id: 45,
      title: "Energy Storage in Renewable Systems",
      situation: `You are presenting about energy storage. The audience asks why it is critical.`,
      expectedAnswer: `Energy storage balances supply and demand, making renewable energy reliable. Batteries store excess energy and stabilize the grid, even when sun or wind isn't available.`,
      type: "respond_to_situation",
    },
    {
      id: 44,
      title: "Debate on Nuclear Power",
      situation: `You are debating nuclear power’s safety and necessity. Share your opinion.`,
      expectedAnswer: `Nuclear energy is low-emission and efficient, but safety protocols are essential. Modern reactors and waste management make it a viable option for climate goals.`,
      type: "respond_to_situation",
    },
    {
      id: 43,
      title: "Geothermal Energy Proposal",
      situation: `A committee asks why geothermal is a strong energy source. Explain.`,
      expectedAnswer: `It provides constant, low-carbon energy with minimal land impact. However, the initial drilling cost and geographic limitation are challenges to consider.`,
      type: "respond_to_situation",
    },
    {
      id: 42,
      title: "Hydropower Sustainability",
      situation: `A government official asks how your hydropower project supports energy needs without harming the ecosystem.`,
      expectedAnswer: `We use fish-friendly turbines and environmental monitoring. Hydropower is renewable and offers flood control, making it a balanced clean energy option.`,
      type: "respond_to_situation",
    },
    {
      id: 41,
      title: "Explaining Wind Energy Simply",
      situation: `A student asks how turbines make electricity. Explain in simple terms.`,
      expectedAnswer: `Wind spins the blades, which turn a generator inside the turbine. This produces electricity the same way water turns a mill or a bike dynamo powers a light.`,
      type: "respond_to_situation",
    },
    {
      id: 40,
      title: "Solar Energy Benefits",
      situation: `You are explaining solar power to investors. Discuss profit and sustainability.`,
      expectedAnswer: `Solar reduces energy costs long-term, and tax incentives increase ROI. It also reduces dependence on fossil fuels and brings environmental benefits.`,
      type: "respond_to_situation",
    },
    {
      id: 39,
      title: "Why Invest in Renewable Energy?",
      situation: `You are giving a presentation on renewables. Explain why investment is essential.`,
      expectedAnswer: `Renewables reduce carbon emissions, create green jobs, and ensure energy independence. They are vital for climate goals and long-term economic health.`,
      type: "respond_to_situation",
    },
    {
      id: 38,
      title: "New Feature for Repeat Visitors",
      situation: `You manage a beach resort and guests rarely return. Propose a feature to boost repeat visits.`,
      expectedAnswer: `Introduce themed seasonal events and loyalty rewards. Adding unique experiences like night beach yoga and locals-only activities create reasons to return.`,
      type: "respond_to_situation",
    },
    {
      id: 37,
      title: "Increasing Ski Resort Tourism",
      situation: `Tourist numbers are low at your ski resort. Suggest how to attract more visitors.`,
      expectedAnswer: `Launch international travel packages, offer inclusive ski lessons, and host winter sports events. Use social media influencers to target younger audiences.`,
      type: "respond_to_situation",
    },
    {
      id: 36,
      title: "Organizing a Cycling Tour",
      situation: `You are planning a city cycling event. Share your ideas for safety and engagement.`,
      expectedAnswer: `Provide clear routes, medical support, and bike checkpoints. Collaborate with local businesses for prizes and involve local media for promotion.`,
      type: "respond_to_situation",
    },
    {
      id: 35,
      title: "Safe and Fun Road Trip Planning",
      situation: `You’re planning a long road trip with friends. Some are worried about costs and safety.`,
      expectedAnswer: `Plan shared expenses, map safe routes, and prepare emergency kits. Use apps to find affordable lodging and summarize daily plans for everyone.`,
      type: "respond_to_situation",
    },
    {
      id: 34,
      title: "Space Tourism Potential",
      situation: `You are speaking on the future of space tourism. Many are skeptical. Give your view.`,
      expectedAnswer: `Though costly and risky today, it drives innovation and inspires STEM interest. With regulation and technology improvements, it can become more accessible.`,
      type: "respond_to_situation",
    },
    {
      id: 33,
      title: "Boosting Festival Tourism",
      situation: `Tourism officials ask how to increase cultural festival participation.`,
      expectedAnswer: `Market festivals through social media, partner with travel agencies, and provide immersive cultural workshops. Festivals reinforce identity and attract visitors.`,
      type: "respond_to_situation",
    },
    {
      id: 32,
      title: "Food Tourism Development",
      situation: `You are organizing a food tourism event. Explain its benefits and strategy.`,
      expectedAnswer: `Food tourism promotes culture and boosts local business. Invite local chefs, showcase regional dishes, and use storytelling to attract culinary travelers.`,
      type: "respond_to_situation",
    },
    {
      id: 31,
      title: "Digital Nomad Lifestyle Pros and Cons",
      situation: `Your colleague wants to become a digital nomad. Share your honest opinion.`,
      expectedAnswer: `It offers flexibility and cultural exposure but requires discipline and internet access. Financial stability and time zone challenges are major concerns.`,
      type: "respond_to_situation",
    },
    {
      id: 30,
      title: "Designing a Vacation Itinerary",
      situation: `A family wants to visit several cities in 10 days. Explain what to consider.`,
      expectedAnswer: `Balance travel time with activities. Group nearby cities, choose flexible transportation, and keep some relaxing days to avoid burnout.`,
      type: "respond_to_situation",
    },
    {
      id: 29,
      title: "Visa-Free Travel Advice",
      situation: `A friend wants to travel without frequent visas. Give advice.`,
      expectedAnswer: `Research passport rankings, explore regional agreements like the Schengen Zone, and use travel forums. Choose countries with visa-on-arrival options.`,
      type: "respond_to_situation",
    },
    {
      id: 28,
      title: "Choosing Travel Insurance",
      situation: `A traveler asks which insurance coverage is essential.`,
      expectedAnswer: `Medical coverage, trip cancellation, and lost baggage protection are must-haves. Compare policies to ensure emergency transport and COVID coverage.`,
      type: "respond_to_situation",
    },
    {
      id: 27,
      title: "Producing Theatre on a Budget",
      situation: `You must produce a show with minimal resources. How?`,
      expectedAnswer: `Use simple sets, creative lighting, and volunteer actors. Partner with local schools for costumes and seek sponsorships for materials.`,
      type: "respond_to_situation",
    },
    {
      id: 26,
      title: "Managing Team Conflicts in Arts",
      situation: `You are directing a performance but the team has conflicts. What do you do?`,
      expectedAnswer: `Hold a mediation meeting, define shared goals, and reassign tasks if needed. Encourage communication and offer individual support.`,
      type: "respond_to_situation",
    },
    {
      id: 25,
      title: "Choosing Documentary Topics",
      situation: `Students don’t know how to pick impactful documentary ideas. Advise them.`,
      expectedAnswer: `Choose topics with emotional depth and clear conflict. Interview diverse perspectives and focus on storytelling, not just facts.`,
      type: "respond_to_situation",
    },
    {
      id: 24,
      title: "Producing a Climate Documentary",
      situation: `A producer asks how to stay on schedule and budget.`,
      expectedAnswer: `Use a tight production timeline, local shooting locations, and clear storyboards. Coordinate daily check-ins and digital backups.`,
      type: "respond_to_situation",
    },
    {
      id: 23,
      title: "Handling a PR Crisis",
      situation: `Your company is criticized online. How do you respond?`,
      expectedAnswer: `Acknowledge concerns quickly, provide transparent updates, and share corrective actions. Engage with audiences to rebuild trust.`,
      type: "respond_to_situation",
    },
    {
      id: 22,
      title: "Ethical Eco-Product Advertising",
      situation: `You are designing an eco-campaign. How will you stand out ethically?`,
      expectedAnswer: `Focus on transparency, real data, and lifestyle branding. Use visuals that inspire without exaggerating environmental claims.`,
      type: "respond_to_situation",
    },
    {
      id: 21,
      title: "Ethical Journalism Practices",
      situation: `Your editor asks how to ensure fair reporting. What do you suggest?`,
      expectedAnswer: `Verify facts, avoid biased language, and protect sources. Use ethical guidelines and peer review to maintain integrity.`,
      type: "respond_to_situation",
    },
    {
      id: 20,
      title: "Social Media Impact on Youth",
      situation: `Discuss whether social media is more helpful or harmful.`,
      expectedAnswer: `It connects, educates, and empowers, but can harm mental health and privacy. Awareness and responsible usage are key to its benefit.`,
      type: "respond_to_situation",
    },
    {
      id: 19,
      title: "Post-Rehab Reintegration",
      situation: `A patient asks how to adjust after rehab. Explain how you help.`,
      expectedAnswer: `Provide support groups, job training, and regular check-ins. Encourage building a positive routine and seeking family support.`,
      type: "respond_to_situation",
    },
    {
      id: 18,
      title: "Accessible Mental Health Plan",
      situation: `Funding agencies ask how your mental health initiative will reach the public.`,
      expectedAnswer: `Offer free screenings, teletherapy, and awareness campaigns. Partner with community centers to reduce stigma and increase access.`,
      type: "respond_to_situation",
    },
    {
      id: 17,
      title: "Homeless Shelter Services",
      situation: `A journalist asks how your shelter helps rebuild lives.`,
      expectedAnswer: `We provide safe housing, counseling, job support, and life skills workshops. Our holistic approach focuses on long-term stability.`,
      type: "respond_to_situation",
    },
    {
      id: 16,
      title: "Meaningful Food Assistance",
      situation: `A volunteer asks how to make a real impact distributing food.`,
      expectedAnswer: `Engage personally, ask about needs, and connect families to resources. Promote education and food security as long-term solutions.`,
      type: "respond_to_situation",
    },
    {
      id: 15,
      title: "Senior Citizen Care Program",
      situation: `You are designing a care program for seniors. What features are essential?`,
      expectedAnswer: `Daily assistance, social activities, health monitoring, and transportation. Programs must foster dignity and prevent isolation.`,
      type: "respond_to_situation",
    },
    {
      id: 14,
      title: "Improving Neighborhood Safety",
      situation: `Residents worry about petty crime. What do you suggest?`,
      expectedAnswer: `Organize a neighborhood watch, improve lighting, and host police workshops. Encourage community bonding and surveillance tools.`,
      type: "respond_to_situation",
    },
    {
      id: 13,
      title: "Improving Government Transparency",
      situation: `The mayor asks for ideas to make services more transparent.`,
      expectedAnswer: `Create an online portal for real-time case tracking and open public feedback channels. Use data dashboards for performance metrics.`,
      type: "respond_to_situation",
    },
    {
      id: 12,
      title: "Why Volunteerism Matters",
      situation: `You are speaking at a youth conference. Many think volunteering is pointless.`,
      expectedAnswer: `Volunteering builds skills, connections, and empathy. It creates change and is often a gateway to career and personal growth.`,
      type: "respond_to_situation",
    },
    {
      id: 11,
      title: "Maintaining Social Cohesion",
      situation: `A forum asks how society stays united despite differences.`,
      expectedAnswer: `Promote intercultural dialogue, inclusive policies, and equal opportunities. Community projects build bridges.`,
      type: "respond_to_situation",
    },
    {
      id: 10,
      title: "Explaining Rural Development Initiatives",
      situation: `Donors want to know how your project helps rural areas.`,
      expectedAnswer: `Our programs focus on irrigation, education, and health care. We empower local communities through microloans and skill training.`,
      type: "respond_to_situation",
    },
    {
      id: 9,
      title: "Sustainable Urban Growth Idea",
      situation: `Pollution and traffic are rising. What do you suggest for sustainable urban planning?`,
      expectedAnswer: `Promote public transit, green zones, and bike lanes. Develop smart infrastructure to reduce emissions and improve mobility.`,
      type: "respond_to_situation",
    },
    {
      id: 8,
      title: "Boosting Community Engagement",
      situation: `Residents show little interest in your project. How do you change this?`,
      expectedAnswer: `Involve schools, host events, and highlight benefits. Give residents ownership and recognition to increase participation.`,
      type: "respond_to_situation",
    },
    {
      id: 7,
      title: "Assessing Franchise Expansion Risks",
      situation: `A franchise owner wants to expand. What should they analyze?`,
      expectedAnswer: `Market demand, management capacity, local regulations, and supply chains are key. Pilot locations help test feasibility.`,
      type: "respond_to_situation",
    },
    {
      id: 6,
      title: "Pitch Improvement for Startups",
      situation: `Founders ask how to improve their investor pitch.`,
      expectedAnswer: `Focus on clear problem-solving, show traction, and include financial projections. Practice storytelling and respond confidently to questions.`,
      type: "respond_to_situation",
    },
    {
      id: 5,
      title: "Ethical Reporting Decision",
      situation: `A colleague suggests manipulating data. What do you do?`,
      expectedAnswer: `Reject the idea, report transparently, and seek alternatives. Integrity and reputation are worth more than short-term gain.`,
      type: "respond_to_situation",
    },
    {
      id: 4,
      title: "Starting an Online Store",
      situation: `A friend wants to sell handmade goods online. Advise them.`,
      expectedAnswer: `Use platforms like Etsy or Shopify. Focus on good product photos, customer service, and consistent social media branding.`,
      type: "respond_to_situation",
    },
    {
      id: 3,
      title: "Marketing for Small Tech Company",
      situation: `Suggest marketing strategies with a tight budget.`,
      expectedAnswer: `Leverage content marketing, influencer partnerships, and free-to-use platforms like YouTube. Focus on storytelling and user testimonials.`,
      type: "respond_to_situation",
    },
    {
      id: 2,
      title: "Corporate Social Responsibility Idea",
      situation: `Your manager asks for a meaningful CSR initiative. Explain your idea.`,
      expectedAnswer: `Launch a community STEM mentorship program. It supports education, aligns with company values, and builds goodwill.`,
      type: "respond_to_situation",
    },
    {
      id: 1,
      title: "Advice for Starting a Small Bakery",
      situation: `You are asked how to start a bakery with limited funds.`,
      expectedAnswer: `Begin with a small menu, rent shared kitchen space, and sell at local markets. Avoid overborrowing; build a loyal base first, then expand.`,
      type: "respond_to_situation",
    },
  ];
  
  export default respondSituations;
  